name: Ungoogled-chromium-archlinux build
on: [push, pull_request]

jobs:
  build:
    env:
        container_name: archlinuxlatest_47dabf
        XHYVE_CPU_COUNT: 4
        XHYVE_MEMORY_SIZE: 11264
    name: Build Chromium
    runs-on: macos-latest

    steps:
      - name: Check Environment
        run: |
            pwd
            uname -r
            system_profiler SPHardwareDataType
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git submodule sync --recursive
            git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Install Docker
        run: |
            brew install docker docker-compose docker-machine xhyve docker-machine-driver-xhyve
            sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
            sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
            brew services start docker-machine
      - name: Create Docker Machine
        run: |
            mkdir -p ~/.docker/machine/cache
            curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.5/boot2docker.iso
            docker-machine create --driver xhyve default
            docker-machine ssh default pwd
            docker-machine ssh default id -un
            docker-machine ssh default mkdir -p /home/docker/work/_temp /home/docker/work/_actions /home/docker/work/_temp/_github_home /home/docker/work/_temp/_github_workflow
      - name: Start Docker
        run: |
            docker-machine env default
            eval "$(docker-machine env default)"
            docker version --format '{{.Server.APIVersion}}'
            docker version --format '{{.Client.APIVersion}}'
            docker ps --all --quiet --no-trunc --filter "label=488dfb"
            docker network prune --force --filter "label=488dfb"
            docker network create --label 488dfb github_network_28ec84219b9a42c98a67ea807a1d376e
            docker pull archlinux:latest
            docker volume create --name ${container_name}_local_volume
            docker create --name ${container_name} --label 488dfb --workdir /__w/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux --network github_network_28ec84219b9a42c98a67ea807a1d376e  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "${container_name}_local_volume":"/__w" -v "/home/docker/work/_temp":"/__w/_temp" -v "/home/docker/work/_actions":"/__w/_actions" -v "/home/docker/work/_temp/_github_home":"/github/home" -v "/home/docker/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" archlinux:latest "-f" "/dev/null"
            docker ps --all
            docker inspect --format "{{range .Config.Env}}{{println .}}{{end}}" ${container_name}
            docker start ${container_name}
      - name: Install dependencies
        run: |
            docker-machine env default
            eval "$(docker-machine env default)"
            docker exec ${container_name} pacman -Sy --noconfirm
            docker exec ${container_name} pacman -S --noconfirm gnu-free-fonts
            docker exec ${container_name} pacman -S --noconfirm --needed base base-devel git
      - name: Move repository
        run: |
            docker-machine env default
            eval "$(docker-machine env default)"
            docker-machine scp -r ../ungoogled-chromium-archlinux docker@default:/home/docker/work/_temp/_github_home
            docker exec ${container_name} bash -c 'cp -r ${HOME}/ungoogled-chromium-archlinux .'
      - name: Create build user
        run: |
            docker-machine env default
            eval "$(docker-machine env default)"
            docker exec ${container_name} useradd builduser -m
            docker exec ${container_name} passwd -d builduser
            docker exec ${container_name} bash -c "printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers"
      - name: Build
        run: |
            docker-machine env default
            eval "$(docker-machine env default)"
            docker exec ${container_name} chown builduser -R ungoogled-chromium-archlinux
            docker exec ${container_name} sudo -u builduser bash -c 'cd ungoogled-chromium-archlinux && makepkg -s --noconfirm' # Clone and build a package
      - name: Move artifact
        env:
            SUMS: checksums.txt
        run: |
            docker-machine env default
            eval "$(docker-machine env default)"
            docker exec ${container_name} bash -c 'ls -la ungoogled-chromium-archlinux'
            docker exec ${container_name} bash -c 'mkdir ${HOME}/artifact && cp ungoogled-chromium-archlinux/*.pkg.* ${HOME}/artifact'
            docker-machine scp -r docker@default:/home/docker/work/_temp/_github_home/artifact ..
            ls -la ..
            cd ../artifact
            openssl sha256 *.pkg.* > $SUMS
            cat $SUMS
      - uses: actions/upload-artifact@master
        name: Upload artifact
        with:
          name: Ungoogled-chromium-archlinux
          path: ../artifact/
