name: Check PKGBUILD
on: [push, pull_request]

jobs:
    build:
        name: "Check PKGBUILD"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout pull request
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Check makepkg
              uses: ungoogled-software/archlinux-check-pkgbuild@master
